<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20230907123014 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE briques_competences_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE competences_globales_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE convention_collective_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE emploi_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE experience_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE fichers_competences_client_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE fiches_competences_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE fiches_postes_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE fiches_postes_generique_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE formation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE parcours_professionnel_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE personne_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE briques_competences (id INT NOT NULL, comp_gb_id INT DEFAULT NULL, rome_id INT DEFAULT NULL, brq_comp_titre TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AE02CD4423E3CEE4 ON briques_competences (comp_gb_id)');
        $this->addSql('CREATE INDEX IDX_AE02CD44EB630B1C ON briques_competences (rome_id)');
        $this->addSql('COMMENT ON COLUMN briques_competences.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN briques_competences.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE competences_globales (id INT NOT NULL, comp_gb_titre TEXT NOT NULL, comp_gb_categorie VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN competences_globales.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN competences_globales.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE convention_collective (id INT NOT NULL, con_coll_titre VARCHAR(100) NOT NULL, con_coll_description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN convention_collective.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN convention_collective.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE emploi (id INT NOT NULL, rome_id INT DEFAULT NULL, fiche_competence_id INT DEFAULT NULL, emploi_titre TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_74A0B0FAEB630B1C ON emploi (rome_id)');
        $this->addSql('CREATE INDEX IDX_74A0B0FA43994995 ON emploi (fiche_competence_id)');
        $this->addSql('COMMENT ON COLUMN emploi.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN emploi.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE experience (id INT NOT NULL, exp_entreprise_id INT DEFAULT NULL, exp_titre VARCHAR(100) NOT NULL, exp_date_debut DATE NOT NULL, exp_date_fin DATE NOT NULL, exp_description TEXT DEFAULT NULL, exp_skills TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_590C1033EC82AC6 ON experience (exp_entreprise_id)');
        $this->addSql('COMMENT ON COLUMN experience.exp_skills IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN experience.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN experience.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE fichers_competences_client (id INT NOT NULL, fic_comp_accreditations_id INT DEFAULT NULL, fic_comp_titre_emploi TEXT NOT NULL, fic_comp_competences_niveau TEXT DEFAULT NULL, fic_comp_version DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_852E172E6E70852C ON fichers_competences_client (fic_comp_accreditations_id)');
        $this->addSql('COMMENT ON COLUMN fichers_competences_client.fic_comp_competences_niveau IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN fichers_competences_client.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN fichers_competences_client.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE fic_comp_competences_client (fichers_competences_client_id INT NOT NULL, briques_competences_id INT NOT NULL, PRIMARY KEY(fichers_competences_client_id, briques_competences_id))');
        $this->addSql('CREATE INDEX IDX_D08DDE928DC72706 ON fic_comp_competences_client (fichers_competences_client_id)');
        $this->addSql('CREATE INDEX IDX_D08DDE92818828AD ON fic_comp_competences_client (briques_competences_id)');
        $this->addSql('CREATE TABLE fiches_competences (id INT NOT NULL, fic_comp_accreditations_id INT DEFAULT NULL, fic_comp_titre_emploi TEXT NOT NULL, fic_comp_competences_niveau TEXT DEFAULT NULL, fic_comp_version DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F0C92A0B6E70852C ON fiches_competences (fic_comp_accreditations_id)');
        $this->addSql('COMMENT ON COLUMN fiches_competences.fic_comp_competences_niveau IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN fiches_competences.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN fiches_competences.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE fiches_competences_briques_competences (fiches_competences_id INT NOT NULL, briques_competences_id INT NOT NULL, PRIMARY KEY(fiches_competences_id, briques_competences_id))');
        $this->addSql('CREATE INDEX IDX_8940993BE7C79C1D ON fiches_competences_briques_competences (fiches_competences_id)');
        $this->addSql('CREATE INDEX IDX_8940993B818828AD ON fiches_competences_briques_competences (briques_competences_id)');
        $this->addSql('CREATE TABLE fiches_postes (id INT NOT NULL, fiches_postes_fiche_competence_id INT DEFAULT NULL, fiches_postes_fiche_rome_id INT DEFAULT NULL, fiches_postes_nplus1_id INT DEFAULT NULL, fiches_postes_entreprise_id INT DEFAULT NULL, fiches_postes_titre TEXT NOT NULL, fiches_postes_validation_at DATE NOT NULL, fiches_postes_visa_at DATE NOT NULL, fiches_postes_activite TEXT DEFAULT NULL, fiches_postes_definition TEXT DEFAULT NULL, fiches_postes_agrement TEXT DEFAULT NULL, conditions_generales TEXT DEFAULT NULL, instructions TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_159DF72453892999 ON fiches_postes (fiches_postes_fiche_competence_id)');
        $this->addSql('CREATE INDEX IDX_159DF724C2C6539B ON fiches_postes (fiches_postes_fiche_rome_id)');
        $this->addSql('CREATE INDEX IDX_159DF724DE3AC2BF ON fiches_postes (fiches_postes_nplus1_id)');
        $this->addSql('CREATE INDEX IDX_159DF724950AACB7 ON fiches_postes (fiches_postes_entreprise_id)');
        $this->addSql('COMMENT ON COLUMN fiches_postes.fiches_postes_activite IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN fiches_postes.fiches_postes_definition IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN fiches_postes.instructions IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN fiches_postes.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN fiches_postes.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE fiches_postes_liaison_hierarchique (fiches_postes_source INT NOT NULL, fiches_postes_target INT NOT NULL, PRIMARY KEY(fiches_postes_source, fiches_postes_target))');
        $this->addSql('CREATE INDEX IDX_CA50D32DB8DE8D2 ON fiches_postes_liaison_hierarchique (fiches_postes_source)');
        $this->addSql('CREATE INDEX IDX_CA50D32C268B85D ON fiches_postes_liaison_hierarchique (fiches_postes_target)');
        $this->addSql('CREATE TABLE fiches_postes_liaison_fonctionnelle (fiches_postes_source INT NOT NULL, fiches_postes_target INT NOT NULL, PRIMARY KEY(fiches_postes_source, fiches_postes_target))');
        $this->addSql('CREATE INDEX IDX_A086D651DB8DE8D2 ON fiches_postes_liaison_fonctionnelle (fiches_postes_source)');
        $this->addSql('CREATE INDEX IDX_A086D651C268B85D ON fiches_postes_liaison_fonctionnelle (fiches_postes_target)');
        $this->addSql('CREATE TABLE fiches_postes_convention_collective (fiches_postes_id INT NOT NULL, convention_collective_id INT NOT NULL, PRIMARY KEY(fiches_postes_id, convention_collective_id))');
        $this->addSql('CREATE INDEX IDX_F3DADE1D8C46B39A ON fiches_postes_convention_collective (fiches_postes_id)');
        $this->addSql('CREATE INDEX IDX_F3DADE1DA3308D98 ON fiches_postes_convention_collective (convention_collective_id)');
        $this->addSql('CREATE TABLE fiches_postes_formations (fiches_postes_id INT NOT NULL, formation_id INT NOT NULL, PRIMARY KEY(fiches_postes_id, formation_id))');
        $this->addSql('CREATE INDEX IDX_E88F20DC8C46B39A ON fiches_postes_formations (fiches_postes_id)');
        $this->addSql('CREATE INDEX IDX_E88F20DC5200282E ON fiches_postes_formations (formation_id)');
        $this->addSql('CREATE TABLE fiches_postes_parcours_professionnel (fiches_postes_id INT NOT NULL, parcours_professionnel_id INT NOT NULL, PRIMARY KEY(fiches_postes_id, parcours_professionnel_id))');
        $this->addSql('CREATE INDEX IDX_C9F0820A8C46B39A ON fiches_postes_parcours_professionnel (fiches_postes_id)');
        $this->addSql('CREATE INDEX IDX_C9F0820A7D110B23 ON fiches_postes_parcours_professionnel (parcours_professionnel_id)');
        $this->addSql('CREATE TABLE fiches_postes_generique (id INT NOT NULL, fic_poste_gen_fiche_competence_id INT DEFAULT NULL, fic_poste_gen_fiche_rome_id INT DEFAULT NULL, fic_poste_gen_nplus1_id INT DEFAULT NULL, fic_poste_gen_entreprise_id INT DEFAULT NULL, fic_poste_gen_titre TEXT NOT NULL, fic_poste_gen_validation_at DATE NOT NULL, fic_poste_gen_visa_at DATE DEFAULT NULL, fic_poste_gen_activite TEXT DEFAULT NULL, fic_poste_gen_definition TEXT DEFAULT NULL, fic_poste_gen_agrement TEXT DEFAULT NULL, fic_poste_gen_conditions_generales TEXT DEFAULT NULL, fic_poste_gen_instructions TEXT DEFAULT NULL, fiches_postes_gen_version DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_42F150C58DB5881F ON fiches_postes_generique (fic_poste_gen_fiche_competence_id)');
        $this->addSql('CREATE INDEX IDX_42F150C58A08E159 ON fiches_postes_generique (fic_poste_gen_fiche_rome_id)');
        $this->addSql('CREATE INDEX IDX_42F150C5596DCDB7 ON fiches_postes_generique (fic_poste_gen_nplus1_id)');
        $this->addSql('CREATE INDEX IDX_42F150C5DDC41E75 ON fiches_postes_generique (fic_poste_gen_entreprise_id)');
        $this->addSql('COMMENT ON COLUMN fiches_postes_generique.fic_poste_gen_activite IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN fiches_postes_generique.fic_poste_gen_definition IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN fiches_postes_generique.fic_poste_gen_instructions IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN fiches_postes_generique.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN fiches_postes_generique.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE fiches_poste_gen_liaison_hierarchique (fiches_postes_generique_id INT NOT NULL, fiches_postes_id INT NOT NULL, PRIMARY KEY(fiches_postes_generique_id, fiches_postes_id))');
        $this->addSql('CREATE INDEX IDX_FF59F12C81240E07 ON fiches_poste_gen_liaison_hierarchique (fiches_postes_generique_id)');
        $this->addSql('CREATE INDEX IDX_FF59F12C8C46B39A ON fiches_poste_gen_liaison_hierarchique (fiches_postes_id)');
        $this->addSql('CREATE TABLE fiches_poste_gen_liaison_fonctionnelle (fiches_postes_generique_id INT NOT NULL, fiches_postes_id INT NOT NULL, PRIMARY KEY(fiches_postes_generique_id, fiches_postes_id))');
        $this->addSql('CREATE INDEX IDX_5A7A17CE81240E07 ON fiches_poste_gen_liaison_fonctionnelle (fiches_postes_generique_id)');
        $this->addSql('CREATE INDEX IDX_5A7A17CE8C46B39A ON fiches_poste_gen_liaison_fonctionnelle (fiches_postes_id)');
        $this->addSql('CREATE TABLE fiches_poste_gen_convention_collective (fiches_postes_generique_id INT NOT NULL, convention_collective_id INT NOT NULL, PRIMARY KEY(fiches_postes_generique_id, convention_collective_id))');
        $this->addSql('CREATE INDEX IDX_9261F8281240E07 ON fiches_poste_gen_convention_collective (fiches_postes_generique_id)');
        $this->addSql('CREATE INDEX IDX_9261F82A3308D98 ON fiches_poste_gen_convention_collective (convention_collective_id)');
        $this->addSql('CREATE TABLE fiches_poste_gen_formations (fiches_postes_generique_id INT NOT NULL, formation_id INT NOT NULL, PRIMARY KEY(fiches_postes_generique_id, formation_id))');
        $this->addSql('CREATE INDEX IDX_F18C3EDF81240E07 ON fiches_poste_gen_formations (fiches_postes_generique_id)');
        $this->addSql('CREATE INDEX IDX_F18C3EDF5200282E ON fiches_poste_gen_formations (formation_id)');
        $this->addSql('CREATE TABLE fiches_poste_gen_fiches_postes_parcours_professionnel (fiches_postes_generique_id INT NOT NULL, parcours_professionnel_id INT NOT NULL, PRIMARY KEY(fiches_postes_generique_id, parcours_professionnel_id))');
        $this->addSql('CREATE INDEX IDX_684F77EE81240E07 ON fiches_poste_gen_fiches_postes_parcours_professionnel (fiches_postes_generique_id)');
        $this->addSql('CREATE INDEX IDX_684F77EE7D110B23 ON fiches_poste_gen_fiches_postes_parcours_professionnel (parcours_professionnel_id)');
        $this->addSql('CREATE TABLE formation (id INT NOT NULL, formation_formateur_id INT DEFAULT NULL, formation_titre VARCHAR(100) NOT NULL, formation_type INT NOT NULL, formation_prerequis TEXT DEFAULT NULL, formation_duree DOUBLE PRECISION NOT NULL, formation_description TEXT DEFAULT NULL, formation_cout INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_404021BF403792D ON formation (formation_formateur_id)');
        $this->addSql('COMMENT ON COLUMN formation.formation_prerequis IS \'(DC2Type:array)\'');
        $this->addSql('COMMENT ON COLUMN formation.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN formation.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE formation_briques_competences (formation_id INT NOT NULL, briques_competences_id INT NOT NULL, PRIMARY KEY(formation_id, briques_competences_id))');
        $this->addSql('CREATE INDEX IDX_2987CC4F5200282E ON formation_briques_competences (formation_id)');
        $this->addSql('CREATE INDEX IDX_2987CC4F818828AD ON formation_briques_competences (briques_competences_id)');
        $this->addSql('CREATE TABLE parcours_professionnel (id INT NOT NULL, par_pro_nom VARCHAR(100) NOT NULL, par_pro_type VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN parcours_professionnel.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN parcours_professionnel.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE personne (id INT NOT NULL, personne_poste_id INT DEFAULT NULL, personne_compte_id INT DEFAULT NULL, personne_nom VARCHAR(50) NOT NULL, personne_prenom VARCHAR(50) DEFAULT NULL, personne_email VARCHAR(100) NOT NULL, personne_telephone VARCHAR(50) NOT NULL, personne_adresse TEXT DEFAULT NULL, personne_genre VARCHAR(1) NOT NULL, personne_date_naissance DATE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FCEC9EF634251C3 ON personne (personne_poste_id)');
        $this->addSql('CREATE INDEX IDX_FCEC9EFF4B0013E ON personne (personne_compte_id)');
        $this->addSql('COMMENT ON COLUMN personne.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN personne.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE personne_experiences (personne_id INT NOT NULL, experience_id INT NOT NULL, PRIMARY KEY(personne_id, experience_id))');
        $this->addSql('CREATE INDEX IDX_8595C321A21BD112 ON personne_experiences (personne_id)');
        $this->addSql('CREATE INDEX IDX_8595C32146E90E27 ON personne_experiences (experience_id)');
        $this->addSql('CREATE TABLE personne_formations (personne_id INT NOT NULL, formation_id INT NOT NULL, PRIMARY KEY(personne_id, formation_id))');
        $this->addSql('CREATE INDEX IDX_BA996933A21BD112 ON personne_formations (personne_id)');
        $this->addSql('CREATE INDEX IDX_BA9969335200282E ON personne_formations (formation_id)');
        $this->addSql('CREATE TABLE personne_accreditations (personne_id INT NOT NULL, accreditation_id INT NOT NULL, PRIMARY KEY(personne_id, accreditation_id))');
        $this->addSql('CREATE INDEX IDX_EE7C8759A21BD112 ON personne_accreditations (personne_id)');
        $this->addSql('CREATE INDEX IDX_EE7C8759A0822E24 ON personne_accreditations (accreditation_id)');
        $this->addSql('ALTER TABLE briques_competences ADD CONSTRAINT FK_AE02CD4423E3CEE4 FOREIGN KEY (comp_gb_id) REFERENCES competences_globales (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE briques_competences ADD CONSTRAINT FK_AE02CD44EB630B1C FOREIGN KEY (rome_id) REFERENCES rome (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emploi ADD CONSTRAINT FK_74A0B0FAEB630B1C FOREIGN KEY (rome_id) REFERENCES rome (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE emploi ADD CONSTRAINT FK_74A0B0FA43994995 FOREIGN KEY (fiche_competence_id) REFERENCES fiches_competences (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE experience ADD CONSTRAINT FK_590C1033EC82AC6 FOREIGN KEY (exp_entreprise_id) REFERENCES entreprise (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fichers_competences_client ADD CONSTRAINT FK_852E172E6E70852C FOREIGN KEY (fic_comp_accreditations_id) REFERENCES accreditation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fic_comp_competences_client ADD CONSTRAINT FK_D08DDE928DC72706 FOREIGN KEY (fichers_competences_client_id) REFERENCES fichers_competences_client (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fic_comp_competences_client ADD CONSTRAINT FK_D08DDE92818828AD FOREIGN KEY (briques_competences_id) REFERENCES briques_competences (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_competences ADD CONSTRAINT FK_F0C92A0B6E70852C FOREIGN KEY (fic_comp_accreditations_id) REFERENCES accreditation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_competences_briques_competences ADD CONSTRAINT FK_8940993BE7C79C1D FOREIGN KEY (fiches_competences_id) REFERENCES fiches_competences (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_competences_briques_competences ADD CONSTRAINT FK_8940993B818828AD FOREIGN KEY (briques_competences_id) REFERENCES briques_competences (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes ADD CONSTRAINT FK_159DF72453892999 FOREIGN KEY (fiches_postes_fiche_competence_id) REFERENCES fiches_competences (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes ADD CONSTRAINT FK_159DF724C2C6539B FOREIGN KEY (fiches_postes_fiche_rome_id) REFERENCES rome (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes ADD CONSTRAINT FK_159DF724DE3AC2BF FOREIGN KEY (fiches_postes_nplus1_id) REFERENCES fiches_postes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes ADD CONSTRAINT FK_159DF724950AACB7 FOREIGN KEY (fiches_postes_entreprise_id) REFERENCES entreprise (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_liaison_hierarchique ADD CONSTRAINT FK_CA50D32DB8DE8D2 FOREIGN KEY (fiches_postes_source) REFERENCES fiches_postes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_liaison_hierarchique ADD CONSTRAINT FK_CA50D32C268B85D FOREIGN KEY (fiches_postes_target) REFERENCES fiches_postes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_liaison_fonctionnelle ADD CONSTRAINT FK_A086D651DB8DE8D2 FOREIGN KEY (fiches_postes_source) REFERENCES fiches_postes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_liaison_fonctionnelle ADD CONSTRAINT FK_A086D651C268B85D FOREIGN KEY (fiches_postes_target) REFERENCES fiches_postes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_convention_collective ADD CONSTRAINT FK_F3DADE1D8C46B39A FOREIGN KEY (fiches_postes_id) REFERENCES fiches_postes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_convention_collective ADD CONSTRAINT FK_F3DADE1DA3308D98 FOREIGN KEY (convention_collective_id) REFERENCES convention_collective (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_formations ADD CONSTRAINT FK_E88F20DC8C46B39A FOREIGN KEY (fiches_postes_id) REFERENCES fiches_postes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_formations ADD CONSTRAINT FK_E88F20DC5200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_parcours_professionnel ADD CONSTRAINT FK_C9F0820A8C46B39A FOREIGN KEY (fiches_postes_id) REFERENCES fiches_postes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_parcours_professionnel ADD CONSTRAINT FK_C9F0820A7D110B23 FOREIGN KEY (parcours_professionnel_id) REFERENCES parcours_professionnel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_generique ADD CONSTRAINT FK_42F150C58DB5881F FOREIGN KEY (fic_poste_gen_fiche_competence_id) REFERENCES fiches_competences (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_generique ADD CONSTRAINT FK_42F150C58A08E159 FOREIGN KEY (fic_poste_gen_fiche_rome_id) REFERENCES rome (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_generique ADD CONSTRAINT FK_42F150C5596DCDB7 FOREIGN KEY (fic_poste_gen_nplus1_id) REFERENCES fiches_postes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_postes_generique ADD CONSTRAINT FK_42F150C5DDC41E75 FOREIGN KEY (fic_poste_gen_entreprise_id) REFERENCES entreprise (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_poste_gen_liaison_hierarchique ADD CONSTRAINT FK_FF59F12C81240E07 FOREIGN KEY (fiches_postes_generique_id) REFERENCES fiches_postes_generique (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_poste_gen_liaison_hierarchique ADD CONSTRAINT FK_FF59F12C8C46B39A FOREIGN KEY (fiches_postes_id) REFERENCES fiches_postes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_poste_gen_liaison_fonctionnelle ADD CONSTRAINT FK_5A7A17CE81240E07 FOREIGN KEY (fiches_postes_generique_id) REFERENCES fiches_postes_generique (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_poste_gen_liaison_fonctionnelle ADD CONSTRAINT FK_5A7A17CE8C46B39A FOREIGN KEY (fiches_postes_id) REFERENCES fiches_postes (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_poste_gen_convention_collective ADD CONSTRAINT FK_9261F8281240E07 FOREIGN KEY (fiches_postes_generique_id) REFERENCES fiches_postes_generique (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_poste_gen_convention_collective ADD CONSTRAINT FK_9261F82A3308D98 FOREIGN KEY (convention_collective_id) REFERENCES convention_collective (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_poste_gen_formations ADD CONSTRAINT FK_F18C3EDF81240E07 FOREIGN KEY (fiches_postes_generique_id) REFERENCES fiches_postes_generique (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_poste_gen_formations ADD CONSTRAINT FK_F18C3EDF5200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_poste_gen_fiches_postes_parcours_professionnel ADD CONSTRAINT FK_684F77EE81240E07 FOREIGN KEY (fiches_postes_generique_id) REFERENCES fiches_postes_generique (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fiches_poste_gen_fiches_postes_parcours_professionnel ADD CONSTRAINT FK_684F77EE7D110B23 FOREIGN KEY (parcours_professionnel_id) REFERENCES parcours_professionnel (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE formation ADD CONSTRAINT FK_404021BF403792D FOREIGN KEY (formation_formateur_id) REFERENCES personne (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE formation_briques_competences ADD CONSTRAINT FK_2987CC4F5200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE formation_briques_competences ADD CONSTRAINT FK_2987CC4F818828AD FOREIGN KEY (briques_competences_id) REFERENCES briques_competences (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne ADD CONSTRAINT FK_FCEC9EF634251C3 FOREIGN KEY (personne_poste_id) REFERENCES fiches_postes (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne ADD CONSTRAINT FK_FCEC9EFF4B0013E FOREIGN KEY (personne_compte_id) REFERENCES compte (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne_experiences ADD CONSTRAINT FK_8595C321A21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne_experiences ADD CONSTRAINT FK_8595C32146E90E27 FOREIGN KEY (experience_id) REFERENCES experience (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne_formations ADD CONSTRAINT FK_BA996933A21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne_formations ADD CONSTRAINT FK_BA9969335200282E FOREIGN KEY (formation_id) REFERENCES formation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne_accreditations ADD CONSTRAINT FK_EE7C8759A21BD112 FOREIGN KEY (personne_id) REFERENCES personne (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE personne_accreditations ADD CONSTRAINT FK_EE7C8759A0822E24 FOREIGN KEY (accreditation_id) REFERENCES accreditation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE fic_comp_competences_client DROP CONSTRAINT FK_D08DDE92818828AD');
        $this->addSql('ALTER TABLE fiches_competences_briques_competences DROP CONSTRAINT FK_8940993B818828AD');
        $this->addSql('ALTER TABLE formation_briques_competences DROP CONSTRAINT FK_2987CC4F818828AD');
        $this->addSql('ALTER TABLE briques_competences DROP CONSTRAINT FK_AE02CD4423E3CEE4');
        $this->addSql('ALTER TABLE fiches_postes_convention_collective DROP CONSTRAINT FK_F3DADE1DA3308D98');
        $this->addSql('ALTER TABLE fiches_poste_gen_convention_collective DROP CONSTRAINT FK_9261F82A3308D98');
        $this->addSql('ALTER TABLE personne_experiences DROP CONSTRAINT FK_8595C32146E90E27');
        $this->addSql('ALTER TABLE fic_comp_competences_client DROP CONSTRAINT FK_D08DDE928DC72706');
        $this->addSql('ALTER TABLE emploi DROP CONSTRAINT FK_74A0B0FA43994995');
        $this->addSql('ALTER TABLE fiches_competences_briques_competences DROP CONSTRAINT FK_8940993BE7C79C1D');
        $this->addSql('ALTER TABLE fiches_postes DROP CONSTRAINT FK_159DF72453892999');
        $this->addSql('ALTER TABLE fiches_postes_generique DROP CONSTRAINT FK_42F150C58DB5881F');
        $this->addSql('ALTER TABLE fiches_postes DROP CONSTRAINT FK_159DF724DE3AC2BF');
        $this->addSql('ALTER TABLE fiches_postes_liaison_hierarchique DROP CONSTRAINT FK_CA50D32DB8DE8D2');
        $this->addSql('ALTER TABLE fiches_postes_liaison_hierarchique DROP CONSTRAINT FK_CA50D32C268B85D');
        $this->addSql('ALTER TABLE fiches_postes_liaison_fonctionnelle DROP CONSTRAINT FK_A086D651DB8DE8D2');
        $this->addSql('ALTER TABLE fiches_postes_liaison_fonctionnelle DROP CONSTRAINT FK_A086D651C268B85D');
        $this->addSql('ALTER TABLE fiches_postes_convention_collective DROP CONSTRAINT FK_F3DADE1D8C46B39A');
        $this->addSql('ALTER TABLE fiches_postes_formations DROP CONSTRAINT FK_E88F20DC8C46B39A');
        $this->addSql('ALTER TABLE fiches_postes_parcours_professionnel DROP CONSTRAINT FK_C9F0820A8C46B39A');
        $this->addSql('ALTER TABLE fiches_postes_generique DROP CONSTRAINT FK_42F150C5596DCDB7');
        $this->addSql('ALTER TABLE fiches_poste_gen_liaison_hierarchique DROP CONSTRAINT FK_FF59F12C8C46B39A');
        $this->addSql('ALTER TABLE fiches_poste_gen_liaison_fonctionnelle DROP CONSTRAINT FK_5A7A17CE8C46B39A');
        $this->addSql('ALTER TABLE personne DROP CONSTRAINT FK_FCEC9EF634251C3');
        $this->addSql('ALTER TABLE fiches_poste_gen_liaison_hierarchique DROP CONSTRAINT FK_FF59F12C81240E07');
        $this->addSql('ALTER TABLE fiches_poste_gen_liaison_fonctionnelle DROP CONSTRAINT FK_5A7A17CE81240E07');
        $this->addSql('ALTER TABLE fiches_poste_gen_convention_collective DROP CONSTRAINT FK_9261F8281240E07');
        $this->addSql('ALTER TABLE fiches_poste_gen_formations DROP CONSTRAINT FK_F18C3EDF81240E07');
        $this->addSql('ALTER TABLE fiches_poste_gen_fiches_postes_parcours_professionnel DROP CONSTRAINT FK_684F77EE81240E07');
        $this->addSql('ALTER TABLE fiches_postes_formations DROP CONSTRAINT FK_E88F20DC5200282E');
        $this->addSql('ALTER TABLE fiches_poste_gen_formations DROP CONSTRAINT FK_F18C3EDF5200282E');
        $this->addSql('ALTER TABLE formation_briques_competences DROP CONSTRAINT FK_2987CC4F5200282E');
        $this->addSql('ALTER TABLE personne_formations DROP CONSTRAINT FK_BA9969335200282E');
        $this->addSql('ALTER TABLE fiches_postes_parcours_professionnel DROP CONSTRAINT FK_C9F0820A7D110B23');
        $this->addSql('ALTER TABLE fiches_poste_gen_fiches_postes_parcours_professionnel DROP CONSTRAINT FK_684F77EE7D110B23');
        $this->addSql('ALTER TABLE formation DROP CONSTRAINT FK_404021BF403792D');
        $this->addSql('ALTER TABLE personne_experiences DROP CONSTRAINT FK_8595C321A21BD112');
        $this->addSql('ALTER TABLE personne_formations DROP CONSTRAINT FK_BA996933A21BD112');
        $this->addSql('ALTER TABLE personne_accreditations DROP CONSTRAINT FK_EE7C8759A21BD112');
        $this->addSql('DROP SEQUENCE briques_competences_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE competences_globales_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE convention_collective_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE emploi_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE experience_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE fichers_competences_client_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE fiches_competences_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE fiches_postes_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE fiches_postes_generique_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE formation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE parcours_professionnel_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE personne_id_seq CASCADE');
        $this->addSql('DROP TABLE briques_competences');
        $this->addSql('DROP TABLE competences_globales');
        $this->addSql('DROP TABLE convention_collective');
        $this->addSql('DROP TABLE emploi');
        $this->addSql('DROP TABLE experience');
        $this->addSql('DROP TABLE fichers_competences_client');
        $this->addSql('DROP TABLE fic_comp_competences_client');
        $this->addSql('DROP TABLE fiches_competences');
        $this->addSql('DROP TABLE fiches_competences_briques_competences');
        $this->addSql('DROP TABLE fiches_postes');
        $this->addSql('DROP TABLE fiches_postes_liaison_hierarchique');
        $this->addSql('DROP TABLE fiches_postes_liaison_fonctionnelle');
        $this->addSql('DROP TABLE fiches_postes_convention_collective');
        $this->addSql('DROP TABLE fiches_postes_formations');
        $this->addSql('DROP TABLE fiches_postes_parcours_professionnel');
        $this->addSql('DROP TABLE fiches_postes_generique');
        $this->addSql('DROP TABLE fiches_poste_gen_liaison_hierarchique');
        $this->addSql('DROP TABLE fiches_poste_gen_liaison_fonctionnelle');
        $this->addSql('DROP TABLE fiches_poste_gen_convention_collective');
        $this->addSql('DROP TABLE fiches_poste_gen_formations');
        $this->addSql('DROP TABLE fiches_poste_gen_fiches_postes_parcours_professionnel');
        $this->addSql('DROP TABLE formation');
        $this->addSql('DROP TABLE formation_briques_competences');
        $this->addSql('DROP TABLE parcours_professionnel');
        $this->addSql('DROP TABLE personne');
        $this->addSql('DROP TABLE personne_experiences');
        $this->addSql('DROP TABLE personne_formations');
        $this->addSql('DROP TABLE personne_accreditations');
    }
}
